### ISSUE TITLE
Hello ! I really like your project but I would recommend you to update Readme.me file to show how to use code

### ISSUE THREAD

**Issue by ferid333** [mesopotamico/basic_Firewall#1]
Hello ! I really like your project but I would recommend you to update Readme.me file to show how to use code

**Comment by mesopotamico** [comment]
You right! Thank you for the feedback.

**Comment by ferid333** [comment]
No problem. You can follow me as you can give feedback to my projects. Thanks !

**Comment by mesopotamico** [comment]
I promise next week to give more details, I appreciate the comments, this is one of my first big projects, the idea is to use this firewall in a distributed system with sockets.

**Comment by ferid333** [comment]
What do you mean with distributed system ? Can you say details ?

**Comment by mesopotamico** [comment]
I am going to implement this on several computers, each one will do a specific task depending on what we need at that moment.

**Comment by ferid333** [comment]
Okay . If you need something or help, just text me

**Comment by mesopotamico** [comment]
Look at the README.me file is now updated and available to use the project, if you have any troubles with the installation or something just tell me.

**Comment by ferid333** [comment]
Great

**Comment by mesopotamico** [comment]
End
